### ISSUE TITLE
add Matomo analytics

### ISSUE THREAD

**Issue by roelandordelman** [beeldengeluid/labs.beeldengeluid.nl#218]
Ik weet niet meer wat we hierover al hadden besproken dus maar even zo. Mijn voorstel zou zijn om bezoek te meten met behulp van Matomo, zoals we ook voor Media Suite en MS Data STories doen. Dan wordt het ook makkelijker om een geaggregeerde count te geven voor de labs. Ik kan in Matomo een apart domein hiervoor maken.

**Comment by phivk** [comment]
@roelandordelman ja laten we Matomo aansluiten. Kun je een nieuwe site aanmaken en het `siteId` hier delen?

klopt deze matomoUrl? 
https://clariah-mediasuite.innocraft.cloud

**Comment by roelandordelman** [comment]
Ik heb de siteId naar je gemaild. De website heeft in Matomo de naam benG-Labs voor url labs.beeldengeluid.nl

**Comment by phivk** [comment]
closed via https://github.com/beeldengeluid/opendatalab/commit/d45e9a011cb6cfcb4b9a1f6207e0f2c6dd38174a

**Comment by phivk** [comment]
@roelandordelman Matomo is toegevoegd in de website code.

Als ik inlog op the matomo backend, en kijk in het 'All Websites Dashboard' ik zie daar geen benG-Labs website staan?
<img width="307" alt="0FCECCC1-F853-42D2-931A-27CB9A609C07-1040-000025E2E7461829" src="https://user-images.githubusercontent.com/902958/153244069-c9162293-54be-443b-95a8-d2be9ad11fd5.png">

**Comment by roelandordelman** [comment]
![Screenshot from 2022-02-09 17-30-50](https://user-images.githubusercontent.com/18610579/153245430-a864143e-7bd7-4197-8943-c4e7bbad483f.png)

**Comment by phivk** [comment]
@roelandordelman als ik inlog op https://clariah-mediasuite.innocraft.cloud/ krijg ik geen BENG-LABS te zien (zoals jij).
is er een setting waarmee je mij toegang kunt geven tot die website?

**Comment by roelandordelman** [comment]
Ik heb je nu toegang gegeven. Moet explicieit voor elke website apart.

**Comment by phivk** [comment]
daarnet in Matomo dashboard gecheckt en het werkt sinds de deployment is voltooid :)
