### ISSUE TITLE
tags rechts op de labs website komen nog niet helemaal overeen met de data

### ISSUE THREAD

**Issue by wmelder** [beeldengeluid/labs.beeldengeluid.nl#266]
tags worden nu geladen uit CMS. 
Deze komen niet helemaal overeen met de datasets. 
Bijv. als je OAI-PMH filtert komt de GTAA bijv. niet naar voren... Dit zou eventueel wel dynamisch kunnen door te kijken naar sdo:encodingFormat, of sdo:usageInfo (beide onderdeel van de distributie/datadownload)
Of andere interessante properties zoals 'language' als tag door naar sdo:inLanguage te kijken... dan haal je die tags niet meer uit het CMS, maar bepaal je deze op basis van interessante properties uit de data. zoals ook sdo:license bijv.

**Comment by phivk** [comment]
Interessante suggestie om tags op de data te baseren. 
Ik denk tot nu toe echter dat ik een voorkeur heb om per dataset in het CMS een lijstje tags bij te houden. Dat geeft meer controle en flexibiliteit. En per dataset wordt er toch al een handmatig een pagina met bijbehorende metadata bijgehouden. Ik zie deze tags vooral als iets wat flexibel wordt bijgehouden door een editor (op basis van gerbuikersbehoeften), ipv als iets dat we systematisch in de code oplossen.

Ready to change my mind op basis van jouw verdere argumenten!

**Comment by phivk** [comment]
aangezien de datasets content vanuit de Markdown worden geladen lijkt het me nuttig om de tags in de Visual te baseren op tags uit die Markdown (de huidige status), waar het makkelijk aan te passen is aan onze voorkeuren.
Mochten we dit willen veranderen dan kan dit issue heropend worden.
