### ISSUE TITLE
deploy to labs.beeldengeluid.nl

### ISSUE THREAD

**Issue by phivk** [beeldengeluid/labs.beeldengeluid.nl#290]
replace former website deployment with new website, with help from @jblom 

see Vercel documentation https://vercel.com/docs/concepts/projects/custom-domains#subdomains

- [x] add custom domain to Vercel project 
- [x] set CNAME record in DNS (via TopDesk)
- [ ] optionally: add proxy (goldfinger) in between for more flexibility in the future

**Comment by jblom** [comment]
@phivk @MartijnBNG it seems this is working now! http://labs.beeldengeluid.nl/nl

Will you close?

**Comment by phivk** [comment]
I confirm, thanks both!

**Comment by phivk** [comment]
reopening as there is still an DNS issue regarding serving over HTTPS

**Comment by phivk** [comment]
solved! https://labs.beeldengeluid.nl/
