### ISSUE TITLE
Add a proper OpenAPI specification to the service layer

### ISSUE THREAD

**Issue by wmelder** [beeldengeluid/labs.beeldengeluid.nl#300]
- [ ] Tweak the OpenAPI file provided by Danny.
- [ ] Provide this at the service layer entrypoint (https://gtaa.apis.beeldengeluid.nl/api)
- [ ] Point to it from the labs website

**Comment by wmelder** [comment]
http://prd-skosapp-bng-01.mam.beeldengeluid.nl/api
this works: https://gtaa.apis.beeldengeluid.nl/autocomplete?text=rutt

**Comment by wmelder** [comment]
afwachten waarop? Ik zou zeggen het is verstandiger om nog even wat te testen voor je het naar productie doorzet. Maar in principe is dit wel de autocomplete omgeving zoals het a-team die zou opleveren.

**Comment by jblom** [comment]
@wmelder ok ik ga NU beginnen met de aansluiting. Dank

**Comment by wmelder** [comment]
@jblom 

door Danny geleverde [yaml ](https://drive.google.com/file/d/1s9XjfoUqA3GI_1xQ_wQmxsqmu9B6AHxg/view?usp=sharing) zou ik nog willen aanpassen aan de paden op het gtaa.apis domein in de proxy server.

Hoe denk jij dat we de aangepaste yaml zouden kunnen laden, zodat het een zinvolle swagger pagina geeft? dus hier => gtaa.apis.beeldengeluid.nl/  

Ik bedoel dus eigenlijk: is het voldoende om de proxy aan te passen met een verwijzing naar een yaml file? Ik denk het niet. Maar hoe dan?

**Comment by wmelder** [comment]
Ook service layer heeft proxy.

Extra regels toegevoegd aan gtaa.apis.beeldengelui.nl.conf.
```apache
  ProxyPass /doc http://prd-skosapp-bng-01.mam.beeldengeluid.nl/doc
  ProxyPassReverse /doc http://prd-skosapp-bng-01.mam.beeldengeluid.nl/doc
```

Met die twee extra proxy rules (zonder slash) krijgen we idd een redirect naar de swagger ui. Maar de URL wordt dan ook omgeschreven incl. de pagina en parameters. Maar ja, ik laat het dan maar even zo. 

Met deze rules zorgen we dat alleen het / pad naar de landingspagine op labs verwijst... Dus niet als er allerlei andere meuk achter slash staat die op geen enkele andere regel matcht.

```apache
  # GENERAL GTAA APIS LANDINGPAGE only redirect with exact match of /
  RewriteEngine on
  RewriteCond %{QUERY_STRING} ^$
  RewriteRule "^/$" "https://labs.beeldengeluid.nl/apis/gtaa" [R,L]
```
