### ISSUE TITLE
metadata for new MOZ dataset doesn't show

### ISSUE THREAD

**Issue by wmelder** [beeldengeluid/labs.beeldengeluid.nl#424]
This page https://labsbeeldengeluidnl-6tedhw4jj-beeldengeluid.vercel.app/nl/datasets/muziekopnamen-zendgemachtigden#metadata
is a deploy from the branch #661_moz_dataset

It doesn't show the metadata tab for the new dataset page in NL. It does show for EN. Maybe it has to be tweaked manually?

**Comment by wmelder** [comment]
@phivk Do you think you can pinpoint the problem? Maybe I can fix this? Would be nice if it is fixed before merging.

**Comment by phivk** [comment]
thanks for reporting, I'll have a look today

**Comment by phivk** [comment]
the NL version of the MOZ dataset description at `content/nl/datasets/muziekopnamen-zendgemachtigden.md` was missing a value for `id`, causing an error during the rendering of metadata in the TabOverview component.
I've added the `id` value:
https://github.com/beeldengeluid/labs.beeldengeluid.nl/pull/423/commits/8a454a13d6e9a6b01477cb00a9cf5c8e63dbbc48
and metadata is now properly displayed:
https://labsbeeldengeluidnl-4k306wm8h-beeldengeluid.vercel.app/nl/datasets/muziekopnamen-zendgemachtigden#metadata

Please close when you are happy with this :)

**Comment by wmelder** [comment]
great catch!
