### ISSUE TITLE
Add audio/video information to dashboard

### ISSUE THREAD

**Issue by mwigham** [beeldengeluid/labs.beeldengeluid.nl#525]
Tasks:
- [x] Create a visualisation for the values of <https://schema.org/associatedMedia>/<https://schema.org/encodingFormat> in the MOZ notebook
- [x] Add this to the example dashboard

**Comment by mwigham** [comment]
This is ready for review. Will we do that ourselves, or do we want to get in touch with Mirjam again (who made the original comment?)

**Comment by KleinRana** [comment]
Roosmarijn wil er na haar vakantie nog even naar kijken, dus deze moet helaas nog even open blijven staan.

**Comment by KleinRana** [comment]
Plan meeting with Roosmarijn & Mari after holidays

**Comment by mwigham** [comment]
Roosmarijn 4/10 gemaild hierover

**Comment by mwigham** [comment]
Besproken met Roosmarijn. We maken geen visualisatie, ik heb deze informatie toegevoegd aan de MOZ beschrijving
